databases:
  - name: tenmansys
    databaseName: tenmansys
    user: tenmansys

services:
  - type: web
    name: tenmansys
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tenmansys
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
