# frozen_string_literal: true

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

User.create(
  username: 'smehsan',
  email: 'admin@tenmansys.com',
  password: 'Ehsan@2022',
  password_confirmation: 'Ehsan@2022'
)

properties = Property.create([
                               # Ehsan Manzil
                               {
                                 name: 'Ehsan Manzil',
                                 landlord: 'Sayed Mohammad Mohsin',
                                 description: 'No Description Required!',
                                 addrline1: 'H.N# 26, Sheikh Para',
                                 addrline2: 'Boalia',
                                 zipcode: '6000',
                                 city: 'Rajshahi',
                                 country: 'BD',
                                 user_id: 1,
                                 contactno: '01711-972177'
                               },
                               # Asa Asiana
                               {
                                 name: 'Asa Asiana',
                                 landlord: 'Hafiz Mahmud & Asa Mahmud',
                                 description: 'No Description Required!',
                                 addrline1: 'H.N# 20, Sheikh Para',
                                 addrline2: 'Boalia',
                                 zipcode: '6000',
                                 city: 'Rajshahi',
                                 country: 'BD',
                                 user_id: 1,
                                 contactno: '01711-972177'
                               }
                             ])

units = Unit.create([
                      # Ehsan Manzil Unit List
                      {
                        user_id: 1,
                        property_id: 1,
                        name: 'Ground Floor',
                        bedroom: 2,
                        bathroom: 2,
                        drawingroom: true,
                        dining: true,
                        kitchen: 1,
                        status: 'occupied',
                        elecmetno: '123456'
                      },
                      {
                        user_id: 1,
                        property_id: 1,
                        name: '3rd Floor(A)',
                        bedroom: 2,
                        bathroom: 1,
                        drawingroom: false,
                        dining: true,
                        kitchen: 1,
                        status: 'occupied',
                        elecmetno: '123456'
                      },
                      {
                        user_id: 1,
                        property_id: 1,
                        name: '3rd Floor(B)',
                        bedroom: 2,
                        bathroom: 1,
                        drawingroom: false,
                        dining: true,
                        kitchen: 1,
                        status: 'occupied',
                        elecmetno: '123456'
                      },
                      {
                        user_id: 1,
                        property_id: 1,
                        name: '4th Floor(A)',
                        bedroom: 2,
                        bathroom: 1,
                        drawingroom: false,
                        dining: true,
                        kitchen: 1,
                        status: 'occupied',
                        elecmetno: '123456'
                      },
                      {
                        user_id: 1,
                        property_id: 1,
                        name: '4th Floor(B)',
                        bedroom: 2,
                        bathroom: 1,
                        drawingroom: false,
                        dining: true,
                        kitchen: 1,
                        status: 'occupied',
                        elecmetno: '123456'
                      },

                      # Asa Aiana Unit List
                      {
                        user_id: 1,
                        property_id: 2,
                        name: 'Ground Floor(A)',
                        bedroom: 2,
                        bathroom: 1,
                        drawingroom: false,
                        dining: true,
                        kitchen: 1,
                        status: 'occupied',
                        elecmetno: '123456'
                      },
                      {
                        user_id: 1,
                        property_id: 2,
                        name: 'Ground Floor(B)',
                        bedroom: 1,
                        bathroom: 1,
                        drawingroom: false,
                        dining: false,
                        kitchen: 0,
                        status: 'occupied',
                        elecmetno: '123456'
                      },
                      {
                        user_id: 1,
                        property_id: 2,
                        name: '1st Floor',
                        bedroom: 2,
                        bathroom: 2,
                        drawingroom: true,
                        dining: true,
                        kitchen: 1,
                        status: 'occupied',
                        elecmetno: '123456'
                      },
                      {
                        user_id: 1,
                        property_id: 2,
                        name: '2nd Floor(A)',
                        bedroom: 2,
                        bathroom: 2,
                        drawingroom: false,
                        dining: true,
                        kitchen: 1,
                        status: 'occupied',
                        elecmetno: '123456'
                      },
                      {
                        user_id: 1,
                        property_id: 2,
                        name: '2nd Floor(B)',
                        bedroom: 1,
                        bathroom: 1,
                        drawingroom: false,
                        dining: false,
                        kitchen: 0,
                        status: 'occupied',
                        elecmetno: '123456'
                      },
                      {
                        user_id: 1,
                        property_id: 2,
                        name: '3rd Floor',
                        bedroom: 2,
                        bathroom: 2,
                        drawingroom: false,
                        dining: true,
                        kitchen: 1,
                        status: 'occupied',
                        elecmetno: '123456'
                      },
                      {
                        user_id: 1,
                        property_id: 2,
                        name: '4th Floor(A)',
                        bedroom: 2,
                        bathroom: 2,
                        drawingroom: false,
                        dining: true,
                        kitchen: 1,
                        status: 'occupied',
                        elecmetno: '123456'
                      },
                      {
                        user_id: 1,
                        property_id: 2,
                        name: '4th Floor(B)',
                        bedroom: 1,
                        bathroom: 1,
                        drawingroom: false,
                        dining: false,
                        kitchen: 0,
                        status: 'occupied',
                        elecmetno: '123456'
                      }
                    ])

tenants = Tenant.create([
                          # Ehsan Manzil Tenants List
                          {
                            user_id: 1,
                            property_id: 1,
                            unit_id: 1,
                            name: 'Mrs. Female Name',
                            nid: '1234567891234',
                            email: 'gf@em.com',
                            mobile: '01711-234567',
                            peraddrline1: 'Address Line 1',
                            peraddrline2: 'Address Line 2',
                            peraddrline3: 'Address Line 3',
                            zipcode: '6000',
                            city: 'Rajshahi',
                            country: 'BD',
                            entrydate: '01/01/2020',
                            exitdate: '',
                            rentpermonth: 8000,
                            advancepaid: 8000,
                            status: 'active'
                          },
                          {
                            user_id: 1,
                            property_id: 1,
                            unit_id: 2,
                            name: 'Mr. Male Name',
                            nid: '1234567891234',
                            email: '3rdu2@em.com',
                            mobile: '01711-234567',
                            peraddrline1: 'Address Line 1',
                            peraddrline2: 'Address Line 2',
                            peraddrline3: 'Address Line 3',
                            zipcode: '6000',
                            city: 'Rajshahi',
                            country: 'BD',
                            entrydate: '01/01/2020',
                            exitdate: '',
                            rentpermonth: 8000,
                            advancepaid: 8000,
                            status: 'active'
                          },
                          {
                            user_id: 1,
                            property_id: 1,
                            unit_id: 3,
                            name: 'Mr. Male Name',
                            nid: '1234567891234',
                            email: '3rdu2@em.com',
                            mobile: '01711-234567',
                            peraddrline1: 'Address Line 1',
                            peraddrline2: 'Address Line 2',
                            peraddrline3: 'Address Line 3',
                            zipcode: '6000',
                            city: 'Rajshahi',
                            country: 'BD',
                            entrydate: '01/01/2020',
                            exitdate: '',
                            rentpermonth: 8000,
                            advancepaid: 8000,
                            status: 'active'
                          },
                          {
                            user_id: 1,
                            property_id: 1,
                            unit_id: 4,
                            name: 'Mr. Male Name',
                            nid: '1234567891234',
                            email: '3rdu2@em.com',
                            mobile: '01711-234567',
                            peraddrline1: 'Address Line 1',
                            peraddrline2: 'Address Line 2',
                            peraddrline3: 'Address Line 3',
                            zipcode: '6000',
                            city: 'Rajshahi',
                            country: 'BD',
                            entrydate: '01/01/2020',
                            exitdate: '',
                            rentpermonth: 8000,
                            advancepaid: 8000,
                            status: 'active'
                          },
                          {
                            user_id: 1,
                            property_id: 1,
                            unit_id: 5,
                            name: 'Mr. Male Name',
                            nid: '1234567891234',
                            email: '3rdu2@em.com',
                            mobile: '01711-234567',
                            peraddrline1: 'Address Line 1',
                            peraddrline2: 'Address Line 2',
                            peraddrline3: 'Address Line 3',
                            zipcode: '6000',
                            city: 'Rajshahi',
                            country: 'BD',
                            entrydate: '01/01/2020',
                            exitdate: '',
                            rentpermonth: 8000,
                            advancepaid: 8000,
                            status: 'active'
                          },
                          # Asa Asiana Tenants List
                          {
                            user_id: 1,
                            property_id: 2,
                            unit_id: 6,
                            name: 'Mr. Male Name',
                            nid: '1234567891234',
                            email: '3rdu2@em.com',
                            mobile: '01711-234567',
                            peraddrline1: 'Address Line 1',
                            peraddrline2: 'Address Line 2',
                            peraddrline3: 'Address Line 3',
                            zipcode: '6000',
                            city: 'Rajshahi',
                            country: 'BD',
                            entrydate: '01/01/2020',
                            exitdate: '',
                            rentpermonth: 8000,
                            advancepaid: 8000,
                            status: 'active'
                          },
                          {
                            user_id: 1,
                            property_id: 2,
                            unit_id: 7,
                            name: 'Mr. Male Name',
                            nid: '1234567891234',
                            email: '3rdu2@em.com',
                            mobile: '01711-234567',
                            peraddrline1: 'Address Line 1',
                            peraddrline2: 'Address Line 2',
                            peraddrline3: 'Address Line 3',
                            zipcode: '6000',
                            city: 'Rajshahi',
                            country: 'BD',
                            entrydate: '01/01/2020',
                            exitdate: '',
                            rentpermonth: 8000,
                            advancepaid: 8000,
                            status: 'active'
                          },
                          {
                            user_id: 1,
                            property_id: 2,
                            unit_id: 8,
                            name: 'Mr. Male Name',
                            nid: '1234567891234',
                            email: '3rdu2@em.com',
                            mobile: '01711-234567',
                            peraddrline1: 'Address Line 1',
                            peraddrline2: 'Address Line 2',
                            peraddrline3: 'Address Line 3',
                            zipcode: '6000',
                            city: 'Rajshahi',
                            country: 'BD',
                            entrydate: '01/01/2020',
                            exitdate: '',
                            rentpermonth: 8000,
                            advancepaid: 8000,
                            status: 'active'
                          },
                          {
                            user_id: 1,
                            property_id: 2,
                            unit_id: 9,
                            name: 'Mr. Male Name',
                            nid: '1234567891234',
                            email: '3rdu2@em.com',
                            mobile: '01711-234567',
                            peraddrline1: 'Address Line 1',
                            peraddrline2: 'Address Line 2',
                            peraddrline3: 'Address Line 3',
                            zipcode: '6000',
                            city: 'Rajshahi',
                            country: 'BD',
                            entrydate: '01/01/2020',
                            exitdate: '',
                            rentpermonth: 8000,
                            advancepaid: 8000,
                            status: 'active'
                          },
                          {
                            user_id: 1,
                            property_id: 2,
                            unit_id: 10,
                            name: 'Mr. Male Name',
                            nid: '1234567891234',
                            email: '3rdu2@em.com',
                            mobile: '01711-234567',
                            peraddrline1: 'Address Line 1',
                            peraddrline2: 'Address Line 2',
                            peraddrline3: 'Address Line 3',
                            zipcode: '6000',
                            city: 'Rajshahi',
                            country: 'BD',
                            entrydate: '01/01/2020',
                            exitdate: '',
                            rentpermonth: 8000,
                            advancepaid: 8000,
                            status: 'active'
                          },
                          {
                            user_id: 1,
                            property_id: 2,
                            unit_id: 11,
                            name: 'Mr. Male Name',
                            nid: '1234567891234',
                            email: '3rdu2@em.com',
                            mobile: '01711-234567',
                            peraddrline1: 'Address Line 1',
                            peraddrline2: 'Address Line 2',
                            peraddrline3: 'Address Line 3',
                            zipcode: '6000',
                            city: 'Rajshahi',
                            country: 'BD',
                            entrydate: '01/01/2020',
                            exitdate: '',
                            rentpermonth: 8000,
                            advancepaid: 8000,
                            status: 'active'
                          },
                          {
                            user_id: 1,
                            property_id: 2,
                            unit_id: 12,
                            name: 'Mr. Male Name',
                            nid: '1234567891234',
                            email: '3rdu2@em.com',
                            mobile: '01711-234567',
                            peraddrline1: 'Address Line 1',
                            peraddrline2: 'Address Line 2',
                            peraddrline3: 'Address Line 3',
                            zipcode: '6000',
                            city: 'Rajshahi',
                            country: 'BD',
                            entrydate: '01/01/2020',
                            exitdate: '',
                            rentpermonth: 8000,
                            advancepaid: 8000,
                            status: 'active'
                          },
                          {
                            user_id: 1,
                            property_id: 2,
                            unit_id: 13,
                            name: 'Mr. Male Name',
                            nid: '1234567891234',
                            email: '3rdu2@em.com',
                            mobile: '01711-234567',
                            peraddrline1: 'Address Line 1',
                            peraddrline2: 'Address Line 2',
                            peraddrline3: 'Address Line 3',
                            zipcode: '6000',
                            city: 'Rajshahi',
                            country: 'BD',
                            entrydate: '01/01/2020',
                            exitdate: '',
                            rentpermonth: 8000,
                            advancepaid: 8000,
                            status: 'active'
                          }
                        ])

rents = Rent.create([
                      {
                        user_id: 1,
                        tenant_id: 1,
                        property_id: 1,
                        rentmonth: '07/01/2022',
                        duedate: '07/01/2022',
                        paymentdate: '07/01/2022',
                        rent: 8000,
                        gassbill: 975,
                        lightbill: 0,
                        waterbill: 0,
                        servicecharge: 200,
                        othercharges: 5,
                        status: 'paid',
                        paymentmode: 'cash',
                        bankname: '',
                        accountnumber: '',
                        refnumber: '',
                        total: '',
                        note: 'Hello Note'
                      },
                      {
                        user_id: 1,
                        tenant_id: 2,
                        property_id: 1,
                        rentmonth: '07/01/2022',
                        duedate: '07/01/2022',
                        paymentdate: '07/01/2022',
                        rent: 8000,
                        gassbill: 975,
                        lightbill: 0,
                        waterbill: 0,
                        servicecharge: 200,
                        othercharges: 5,
                        status: 'paid',
                        paymentmode: 'cash',
                        bankname: '',
                        accountnumber: '',
                        refnumber: '',
                        total: '',
                        note: 'Hello Note'
                      },
                      {
                        user_id: 1,
                        tenant_id: 3,
                        property_id: 1,
                        rentmonth: '07/01/2022',
                        duedate: '07/01/2022',
                        paymentdate: '07/01/2022',
                        rent: 8000,
                        gassbill: 975,
                        lightbill: 0,
                        waterbill: 0,
                        servicecharge: 200,
                        othercharges: 5,
                        status: 'paid',
                        paymentmode: 'cash',
                        bankname: '',
                        accountnumber: '',
                        refnumber: '',
                        total: '',
                        note: 'Hello Note'
                      },
                      {
                        user_id: 1,
                        tenant_id: 4,
                        property_id: 1,
                        rentmonth: '07/01/2022',
                        duedate: '07/01/2022',
                        paymentdate: '07/01/2022',
                        rent: 8000,
                        gassbill: 975,
                        lightbill: 0,
                        waterbill: 0,
                        servicecharge: 200,
                        othercharges: 5,
                        status: 'paid',
                        paymentmode: 'cash',
                        bankname: '',
                        accountnumber: '',
                        refnumber: '',
                        total: '',
                        note: 'Hello Note'
                      },
                      {
                        user_id: 1,
                        tenant_id: 5,
                        property_id: 1,
                        rentmonth: '07/01/2022',
                        duedate: '07/01/2022',
                        paymentdate: '07/01/2022',
                        rent: 6000,
                        gassbill: 975,
                        lightbill: 0,
                        waterbill: 0,
                        servicecharge: 200,
                        othercharges: 5,
                        status: 'paid',
                        paymentmode: 'cash',
                        bankname: '',
                        accountnumber: '',
                        refnumber: '',
                        total: '',
                        note: 'Hello Note'
                      },

                      {
                        user_id: 1,
                        tenant_id: 6,
                        property_id: 2,
                        rentmonth: '07/01/2022',
                        duedate: '07/01/2022',
                        paymentdate: '07/01/2022',
                        rent: 6000,
                        gassbill: 975,
                        lightbill: 0,
                        waterbill: 0,
                        servicecharge: 200,
                        othercharges: 5,
                        status: 'paid',
                        paymentmode: 'cash',
                        bankname: '',
                        accountnumber: '',
                        refnumber: '',
                        total: '',
                        note: 'Hello Note'
                      },
                      {
                        user_id: 1,
                        tenant_id: 7,
                        property_id: 2,
                        rentmonth: '07/01/2022',
                        duedate: '07/01/2022',
                        paymentdate: '07/01/2022',
                        rent: 4000,
                        gassbill: 975,
                        lightbill: 0,
                        waterbill: 0,
                        servicecharge: 200,
                        othercharges: 5,
                        status: 'paid',
                        paymentmode: 'cash',
                        bankname: '',
                        accountnumber: '',
                        refnumber: '',
                        total: '',
                        note: 'Hello Note'
                      },
                      {
                        user_id: 1,
                        tenant_id: 8,
                        property_id: 2,
                        rentmonth: '07/01/2022',
                        duedate: '07/01/2022',
                        paymentdate: '07/01/2022',
                        rent: 9000,
                        gassbill: 975,
                        lightbill: 0,
                        waterbill: 0,
                        servicecharge: 200,
                        othercharges: 5,
                        status: 'paid',
                        paymentmode: 'cash',
                        bankname: '',
                        accountnumber: '',
                        refnumber: '',
                        total: '',
                        note: 'Hello Note'
                      },
                      {
                        user_id: 1,
                        tenant_id: 9,
                        property_id: 2,
                        rentmonth: '07/01/2022',
                        duedate: '07/01/2022',
                        paymentdate: '07/01/2022',
                        rent: 8000,
                        gassbill: 975,
                        lightbill: 0,
                        waterbill: 0,
                        servicecharge: 100,
                        othercharges: 5,
                        status: 'paid',
                        paymentmode: 'cash',
                        bankname: '',
                        accountnumber: '',
                        refnumber: '',
                        total: '',
                        note: 'Hello Note'
                      },
                      {
                        user_id: 1,
                        tenant_id: 10,
                        property_id: 2,
                        rentmonth: '07/01/2022',
                        duedate: '07/01/2022',
                        paymentdate: '07/01/2022',
                        rent: 8000,
                        gassbill: 975,
                        lightbill: 0,
                        waterbill: 0,
                        servicecharge: 100,
                        othercharges: 5,
                        status: 'paid',
                        paymentmode: 'cash',
                        bankname: '',
                        accountnumber: '',
                        refnumber: '',
                        total: '',
                        note: 'Hello Note'
                      },
                      {
                        user_id: 1,
                        tenant_id: 11,
                        property_id: 2,
                        rentmonth: '07/01/2022',
                        duedate: '07/01/2022',
                        paymentdate: '07/01/2022',
                        rent: 4000,
                        gassbill: 0,
                        lightbill: 0,
                        waterbill: 0,
                        servicecharge: 100,
                        othercharges: 5,
                        status: 'paid',
                        paymentmode: 'cash',
                        bankname: '',
                        accountnumber: '',
                        refnumber: '',
                        total: '',
                        note: 'Hello Note'
                      },
                      {
                        user_id: 1,
                        tenant_id: 12,
                        property_id: 2,
                        rentmonth: '07/01/2022',
                        duedate: '07/01/2022',
                        paymentdate: '07/01/2022',
                        rent: 6000,
                        gassbill: 975,
                        lightbill: 0,
                        waterbill: 0,
                        servicecharge: 100,
                        othercharges: 5,
                        status: 'paid',
                        paymentmode: 'cash',
                        bankname: '',
                        accountnumber: '',
                        refnumber: '',
                        total: '',
                        note: 'Hello Note'
                      },
                      {
                        user_id: 1,
                        tenant_id: 13,
                        property_id: 2,
                        rentmonth: '07/01/2022',
                        duedate: '07/01/2022',
                        paymentdate: '07/01/2022',
                        rent: 6000,
                        gassbill: 975,
                        lightbill: 0,
                        waterbill: 0,
                        servicecharge: 100,
                        othercharges: 5,
                        status: 'paid',
                        paymentmode: 'cash',
                        bankname: '',
                        accountnumber: '',
                        refnumber: '',
                        total: '',
                        note: 'Hello Note'
                      }
                    ])
